import { elevador,
    bar,
    bell,
    child,
    cine,
    fire,
    fuego,
    game,
    garaje,
    garden,
    gym,
    hamaca,
    jacuzzi,
    maletin,
    meditacion,
    parrilla,
    pool,
    restaurante,
    salon,
    secadora,
    spa,
    telescopio,
    terraza,
    yoga } from "../assets";

export const amenities = [
    { id: 400, icon: garaje, label: 'Cocheras' },
    { id: 401, icon: garden, label: 'Jardines' },
    { id: 402, icon: terraza, label: 'Terraza' },
    { id: 403, icon: gym, label: 'Gimnasio' },
    { id: 404, icon: salon, label: 'Sala de Reuniones' },
    { id: 405, icon: bar, label: 'Bar' },
    { id: 406, icon: bell, label: 'Conserje' },
    { id: 407, icon: child, label: 'Área de Juegos para Niños' },
    { id: 408, icon: cine, label: 'Cine' },
    { id: 409, icon: fire, label: 'Chimenea' },
    { id: 410, icon: fuego, label: 'Fogata' },
    { id: 411, icon: game, label: 'Sala de Juegos' },
    { id: 412, icon: hamaca, label: 'Hamacas' },
    { id: 413, icon: jacuzzi, label: 'Jacuzzi' },
    { id: 414, icon: maletin, label: 'Oficinas' },
    { id: 415, icon: meditacion, label: 'Sala de Meditación' },
    { id: 416, icon: parrilla, label: 'Parrillas' },
    { id: 417, icon: pool, label: 'Piscina' },
    { id: 418, icon: restaurante, label: 'Restaurante' },
    { id: 419, icon: secadora, label: 'Secadora de Ropa' },
    { id: 420, icon: spa, label: 'Spa' },
    { id: 421, icon: telescopio, label: 'Observatorio' },
    { id: 422, icon: yoga, label: 'Sala de Yoga' },
    { id: 423, icon: elevador, label: 'Ascensor' }
];
